services:
  vote:
    image: unclewowa/examplevotingapp_vote:v1
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: unclewowa/examplevotingapp_result:v1
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    image: unclewowa/examplevotingapp_worker:v1
    networks:
      - back-tier

  redis:
    image: redis:alpine
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  database:

networks:
  front-tier:
  back-tier:
